repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-bugbear ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "-r", "bot-pilot-chat/backend/src" ]
        exclude: 'tests/|test_.*\.py$'

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # aktuelle Version pr√ºfen
    hooks:
      - id: detect-secrets
        args: [ "--baseline", ".secrets.baseline" ]

  # üåê Frontend Code: ESLint + Prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
      - id: eslint
        name: eslint (frontend)
        entry: yarn lint
        language: system
        types: [ javascript, jsx, ts, tsx ]
        pass_filenames: false
        additional_dependencies: [ ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies: [ "prettier" ]
        files: ^chat-bot-pilot/frontend/.*\.(ts|tsx)$
