language: de

pipeline:
  - name: SpacyNLP
    model: "de_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    epochs: 100
    batch_size: 50
    max_training_samples: 300
  - name: AugmentedMemoizationPolicy
    max_history: 5
assistant_id: 20250805-174126-insulated-chief
