language: de

pipeline:
  - name: SpacyNLP
    model: "de_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier
    threshold: 0.6

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.6
    core_fallback_action_name: "utter_please_rephrase"
    enable_fallback_prediction: True

assistant_id: 20250805-174126-insulated-chief
