name: Bot-Pilot Core CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
      - './bot-pilot-chat/backend/rasa-actions/**'
      - './.github/workflows/bot-pilot-core-image.yml.yml'

jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true || ${{github.event == 'workflow_dispatch'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository bot-pilot
        uses: actions/checkout@v5
      - name: Checkout repository bot-pilot-config
        uses: actions/checkout@v5
        with:
          repository: normanboettcher/bot-pilot-config
          token: ${{ secrets.BOT_PILOT_CONFIG_TOKEN }}
          path: bot-pilot-config

      - name: Log in to docker.io
        uses: ./.github/workflows/docker-actions/action.yml
      - name: Build and Push bot-pilot-core container image
        uses: docker/build-push-action@v6
        with:
          context: bot-pilot-chat/backend/rasa-actions
          file: bot-pilot-config/deployment/backend/core/Containerfile
          push: true
          tags: docker.io/normanboettcher/bot-pilot:bot-pilot-core-latest