name: BotPilot Connectors CI

on:
  push:
    paths:
      - './bot-pilot-chat/backend/bot-connectors/**'
      - '.github/workflows/bot-connectors.yml'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: .tox cache
        uses: actions/cache@v4
        with:
          path: bot-pilot-chat/backend/bot-connectors/.tox
          key: ${{ runner.os }}-tox-lint-${{ github.ref_name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
        working-directory: bot-pilot-chat/backend/bot-connectors
      - name: Run linting
        run: make lint
        working-directory: bot-pilot-chat/backend/bot-connectors
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: .tox cache
        uses: actions/cache@v4
        with:
          path: bot-pilot-chat/backend/bot-connectors/.tox
          key: ${{ runner.os }}-tox-test-${{ github.ref_name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
        working-directory: bot-pilot-chat/backend/bot-connectors
      - name: Run unit tests
        run: make test
        working-directory: bot-pilot-chat/backend/bot-connectors