name: Connectors Image CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
      - './bot-pilot-chat/backend/bot-connectors/**'
      - '.github/workflows/connectors-image.yml'

jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true || ${{github.event == 'workflow_dispatch'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository bot-pilot
        uses: actions/checkout@v5
      - name: Checkout repository bot-pilot-config
        uses: actions/checkout@v5
        with:
          repository: normanboettcher/bot-pilot-config
          token: ${{ secrets.BOT_PILOT_CONFIG_TOKEN }}
          path: bot-pilot-config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push bot-connectors container image
        uses: docker/build-push-action@v6
        with:
          context: bot-pilot-chat/backend/bot-connectors
          file: bot-pilot-config/deployment/backend/connectors/Containerfile
          push: true
          tags: docker.io/normanboettcher/bot-pilot:bot-connectors-latest