name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true || ${{github.event == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository bot-pilot
        uses: actions/checkout@v5
      - name: Checkout repository bot-pilot-config
        uses: actions/checkout@v5
        with:
          repository: normanboettcher/bot-pilot-config
          token: ${{ secrets.BOT_PILOT_CONFIG_TOKEN }}
          path: bot-pilot-config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Copy .env.development file into context directory
        run: |
          cp bot-pilot-config/deployment/frontend/.env.development bot-pilot-chat/frontend
      
      - name: Build and Push Frontend container image
        uses: docker/build-push-action@v6
        with:
          context: bot-pilot-chat/frontend/
          file: bot-pilot-config/deployment/frontend/Containerfile
          push: true
          build-args: |
            MODE=development
          tags: docker.io/normanboettcher/bot-pilot:frontend-latest
      - name: Build an Push bot-pilot-core container image
        uses: docker/build-push-action@v6
        with:
          context: bot-pilot-chat/backend/rasa-actions
          file: bot-pilot-config/deployment/backend/core/Containerfile
          push: true
          tags: docker.io/normanboettcher/bot-pilot:bot-pilot-core-latest
      
      
    
    

        
