name: BotPilot Rasa Actions CI

on:
  push:
    paths:
      - 'bot-pilot-chat/backend/rasa-actions/**'
      - '.github/workflows/rasa-actions.yml'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: .tox cache
        uses: actions/cache@v4
        with:
          path: bot-pilot-chat/backend/rasa-actions/.tox
          key: ${{ runner.os }}-tox-lint-${{ github.ref_name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==4.31.0
        working-directory: bot-pilot-chat/backend/rasa-actions
      - name: Run linting
        run: make lint
        working-directory: bot-pilot-chat/backend/rasa-actions

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: .tox cache
        uses: actions/cache@v4
        with:
          path: bot-pilot-chat/backend/rasa-actions/.tox
          key: ${{ runner.os }}-tox-test-${{ github.ref_name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==4.31.0
        working-directory: bot-pilot-chat/backend/rasa-actions
      - name: Run unit tests
        run: make unit_test
        working-directory: bot-pilot-chat/backend/rasa-actions
      - name: run rasa tests
        run: make rasa_test
        working-directory: bot-pilot-chat/backend/rasa-actions