name: BotPilot Rasa Actions CI

on:
  push:
    paths:
      - 'bot-pilot-chat/backend/rasa-actions/**'
      - '.github/workflows/rasa-actions.yml'
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot-pilot-chat/backend/rasa-actions
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-env-rasa-actions
      - name: Run linting
        run: tox -e lint

  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot-pilot-chat/backend/rasa-actions
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-env-rasa-actions
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: tox -e unit_tests

  rasa_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot-pilot-chat/backend/rasa-actions
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-env-rasa-actions
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: tox -e rasa_tests


