name: Frontend Webapp CI
on:
  push:
    paths:
      - 'bot-pilot-web/chatme-web-app/**'
      - '.github/workflows/web-frontend.yml'
  pull_request:
    paths:
      - 'bot-pilot-web/chatme-web-app/**'
jobs:
  build:
    name: Build Webapp
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bot-pilot-web/chatme-web-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.16.0 with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Enable Corepack and activate Yarn 4.9.2
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
        working-directory: bot-pilot-web/chatme-web-app

      - name: Run Unit Tests
        run: yarn test:unit

      - name: Build frontend
        run: yarn build
